// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4mtRQRNuvpCv9kF9OWeFYqqvR2Erj0Ec',
    appId: '1:1028410693930:web:16b5ae8166110f3adba653',
    messagingSenderId: '1028410693930',
    projectId: 'social-media-app-5609e',
    authDomain: 'social-media-app-5609e.firebaseapp.com',
    storageBucket: 'social-media-app-5609e.appspot.com',
    measurementId: 'G-155QRD69SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX1Q5KHRz2eHFvt7R32DRdlefkuY9qZ1g',
    appId: '1:1028410693930:android:d20cf033fe2a06d4dba653',
    messagingSenderId: '1028410693930',
    projectId: 'social-media-app-5609e',
    storageBucket: 'social-media-app-5609e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAydEBmcvEuwghJs1RYtGYp7dqS-GNleco',
    appId: '1:1028410693930:ios:263741e3af5a43a6dba653',
    messagingSenderId: '1028410693930',
    projectId: 'social-media-app-5609e',
    storageBucket: 'social-media-app-5609e.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
